# Generated by Django 3.0.7 on 2020-06-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='link',
            field=models.CharField(default='destinations.html', max_length=20),
            preserve_default=False,
        ),
    ]
