# Generated by Django 3.0.7 on 2020-07-01 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0002_destination_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='destination',
            old_name='link',
            new_name='action',
        ),
    ]
